### ISSUE TITLE
Some Parameters of JSON are not Converted to ABAP Data

### ISSUE THREAD

**Issue by Sandy221115** [SAP-samples/abap-platform-jak#2]
@SebastianWolf-SAP 

I am not able to get all the parameters in the below JSON to ABAP Data, Kindly Help me.

{"stjCd":"AP003","lgnm":"MS CORPORATION","nba":["Bonded Warehouse","EOU / STP / EHTP","Factory / Manufacturing","Input Service Distributor (ISD)","Leasing Business"],"adadr":[{"addr":{"bnm":"ELPHINSTONE BUILDING","pncd":"400001"},"ntr":["Wholesale Business"]}],"pradr":{"addr":{"bnm":"KATGARA HOUSE","pncd":"400006"},"ntr":["Wholesale Business"]}}

**Comment by SebastianWolf-SAP** [comment]
Please note that this project is sample code (see license) and should therefore not be used in productive environments. As a consequence, the code might work or might not work... 

But I might have a look - could you please post your ABAP type definition which you used and also specify which elements were not converted? Thanks!

**Comment by Sandy221115** [comment]
@SebastianWolf-SAP,
Thanks for you reponse...

Actually i am doing some R&D , not using in the productive environment

ABAP Type:
@EndUserText.label : 'Search  Taxpayer Str'
@AbapCatalog.enhancementCategory : #NOT_EXTENSIBLE
define structure zsearch_taxpayer_str {
  stjcd    : abap.string(0);
  lgnm     : abap.string(0);
  stj      : abap.string(0);
  dty      : abap.string(0);
  cxdt     : abap.string(0);
  gstin    : abap.string(0);
  nba      : zstring_table;
  lstupdt  : abap.string(0);
  rgdt     : abap.string(0);
  ctb      : abap.string(0);
  sts      : abap.string(0);
  ctjcd    : abap.string(0);
  ctj      : abap.string(0);
  tradenam : abap.string(0);
  adadr    : zstx_adadr_tt;  (structure: ZSTX_ADADR_STR)
  pradr    : zstx_adadr_str;

}



@EndUserText.label : 'ADADR Str'
@AbapCatalog.enhancementCategory : #NOT_EXTENSIBLE
define structure zstx_adadr_str {
  addr : ztaxpayer_addr_str;
  ntr  : zstring_table;

}

@EndUserText.label : 'Taxpayer Address Str'
@AbapCatalog.enhancementCategory : #NOT_EXTENSIBLE
define structure ztaxpayer_addr_str {
  bnm  : abap.string(0);
  st   : abap.string(0);
  loc  : abap.string(0);
  bno  : abap.string(0);
  stcd : abap.string(0);
  flno : abap.string(0);
  lt   : abap.string(0);
  lg   : abap.string(0);
  pncd : abap.string(0);

}

Below Elements are not converted
nba
pradr
adadr

**Comment by SebastianWolf-SAP** [comment]
Thanks for the sample type definitions. I actually had some time to take a look and the respective JSON elements were simply not implemented (correctly). Please check out the newest revision - be sure to sync abap-platform-yy as well as changes were needed there as well. 

Looking forward to your feedback! Feel free to reopen the issue in case something is still not working...

**Comment by Sandy221115** [comment]
@SebastianWolf-SAP  thanks for the changes
